/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as RegisterImport } from "./routes/register";
import { Route as LoginImport } from "./routes/login";
import { Route as IndexImport } from "./routes/index";
import { Route as ExperiencesExperienceIdIndexImport } from "./routes/experiences/$experienceId/index";
import { Route as ExperiencesExperienceIdEditImport } from "./routes/experiences/$experienceId/edit";

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ExperiencesExperienceIdIndexRoute =
  ExperiencesExperienceIdIndexImport.update({
    id: "/experiences/$experienceId/",
    path: "/experiences/$experienceId/",
    getParentRoute: () => rootRoute,
  } as any);

const ExperiencesExperienceIdEditRoute =
  ExperiencesExperienceIdEditImport.update({
    id: "/experiences/$experienceId/edit",
    path: "/experiences/$experienceId/edit",
    getParentRoute: () => rootRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    "/experiences/$experienceId/edit": {
      id: "/experiences/$experienceId/edit";
      path: "/experiences/$experienceId/edit";
      fullPath: "/experiences/$experienceId/edit";
      preLoaderRoute: typeof ExperiencesExperienceIdEditImport;
      parentRoute: typeof rootRoute;
    };
    "/experiences/$experienceId/": {
      id: "/experiences/$experienceId/";
      path: "/experiences/$experienceId";
      fullPath: "/experiences/$experienceId";
      preLoaderRoute: typeof ExperiencesExperienceIdIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/experiences/$experienceId/edit": typeof ExperiencesExperienceIdEditRoute;
  "/experiences/$experienceId": typeof ExperiencesExperienceIdIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/experiences/$experienceId/edit": typeof ExperiencesExperienceIdEditRoute;
  "/experiences/$experienceId": typeof ExperiencesExperienceIdIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/experiences/$experienceId/edit": typeof ExperiencesExperienceIdEditRoute;
  "/experiences/$experienceId/": typeof ExperiencesExperienceIdIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/register"
    | "/experiences/$experienceId/edit"
    | "/experiences/$experienceId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/register"
    | "/experiences/$experienceId/edit"
    | "/experiences/$experienceId";
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/register"
    | "/experiences/$experienceId/edit"
    | "/experiences/$experienceId/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  ExperiencesExperienceIdEditRoute: typeof ExperiencesExperienceIdEditRoute;
  ExperiencesExperienceIdIndexRoute: typeof ExperiencesExperienceIdIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ExperiencesExperienceIdEditRoute: ExperiencesExperienceIdEditRoute,
  ExperiencesExperienceIdIndexRoute: ExperiencesExperienceIdIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/register",
        "/experiences/$experienceId/edit",
        "/experiences/$experienceId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/experiences/$experienceId/edit": {
      "filePath": "experiences/$experienceId/edit.tsx"
    },
    "/experiences/$experienceId/": {
      "filePath": "experiences/$experienceId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
