/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as UsersUserIdIndexImport } from './routes/users/$userId/index'
import { Route as ExperiencesExperienceIdIndexImport } from './routes/experiences/$experienceId/index'
import { Route as UsersUserIdFollowingImport } from './routes/users/$userId/following'
import { Route as UsersUserIdFollowersImport } from './routes/users/$userId/followers'
import { Route as UsersUserIdEditImport } from './routes/users/$userId/edit'
import { Route as ExperiencesExperienceIdEditImport } from './routes/experiences/$experienceId/edit'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdIndexRoute = UsersUserIdIndexImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesExperienceIdIndexRoute =
  ExperiencesExperienceIdIndexImport.update({
    id: '/experiences/$experienceId/',
    path: '/experiences/$experienceId/',
    getParentRoute: () => rootRoute,
  } as any)

const UsersUserIdFollowingRoute = UsersUserIdFollowingImport.update({
  id: '/users/$userId/following',
  path: '/users/$userId/following',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdFollowersRoute = UsersUserIdFollowersImport.update({
  id: '/users/$userId/followers',
  path: '/users/$userId/followers',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdEditRoute = UsersUserIdEditImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesExperienceIdEditRoute =
  ExperiencesExperienceIdEditImport.update({
    id: '/experiences/$experienceId/edit',
    path: '/experiences/$experienceId/edit',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/experiences/$experienceId/edit': {
      id: '/experiences/$experienceId/edit'
      path: '/experiences/$experienceId/edit'
      fullPath: '/experiences/$experienceId/edit'
      preLoaderRoute: typeof ExperiencesExperienceIdEditImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/followers': {
      id: '/users/$userId/followers'
      path: '/users/$userId/followers'
      fullPath: '/users/$userId/followers'
      preLoaderRoute: typeof UsersUserIdFollowersImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/following': {
      id: '/users/$userId/following'
      path: '/users/$userId/following'
      fullPath: '/users/$userId/following'
      preLoaderRoute: typeof UsersUserIdFollowingImport
      parentRoute: typeof rootRoute
    }
    '/experiences/$experienceId/': {
      id: '/experiences/$experienceId/'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof ExperiencesExperienceIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/experiences/$experienceId/edit': typeof ExperiencesExperienceIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/users/$userId/followers': typeof UsersUserIdFollowersRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/experiences/$experienceId/edit': typeof ExperiencesExperienceIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/users/$userId/followers': typeof UsersUserIdFollowersRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/experiences/$experienceId/edit': typeof ExperiencesExperienceIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/users/$userId/followers': typeof UsersUserIdFollowersRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/experiences/$experienceId/': typeof ExperiencesExperienceIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/experiences/$experienceId/edit'
    | '/users/$userId/edit'
    | '/users/$userId/followers'
    | '/users/$userId/following'
    | '/experiences/$experienceId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/experiences/$experienceId/edit'
    | '/users/$userId/edit'
    | '/users/$userId/followers'
    | '/users/$userId/following'
    | '/experiences/$experienceId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/experiences/$experienceId/edit'
    | '/users/$userId/edit'
    | '/users/$userId/followers'
    | '/users/$userId/following'
    | '/experiences/$experienceId/'
    | '/users/$userId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ExperiencesExperienceIdEditRoute: typeof ExperiencesExperienceIdEditRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
  UsersUserIdFollowersRoute: typeof UsersUserIdFollowersRoute
  UsersUserIdFollowingRoute: typeof UsersUserIdFollowingRoute
  ExperiencesExperienceIdIndexRoute: typeof ExperiencesExperienceIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ExperiencesExperienceIdEditRoute: ExperiencesExperienceIdEditRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
  UsersUserIdFollowersRoute: UsersUserIdFollowersRoute,
  UsersUserIdFollowingRoute: UsersUserIdFollowingRoute,
  ExperiencesExperienceIdIndexRoute: ExperiencesExperienceIdIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/register",
        "/experiences/$experienceId/edit",
        "/users/$userId/edit",
        "/users/$userId/followers",
        "/users/$userId/following",
        "/experiences/$experienceId/",
        "/users/$userId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/experiences/$experienceId/edit": {
      "filePath": "experiences/$experienceId/edit.tsx"
    },
    "/users/$userId/edit": {
      "filePath": "users/$userId/edit.tsx"
    },
    "/users/$userId/followers": {
      "filePath": "users/$userId/followers.tsx"
    },
    "/users/$userId/following": {
      "filePath": "users/$userId/following.tsx"
    },
    "/experiences/$experienceId/": {
      "filePath": "experiences/$experienceId/index.tsx"
    },
    "/users/$userId/": {
      "filePath": "users/$userId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
