/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as ExperiencesExperienceIdImport } from "./routes/experiences/$experienceId";
import { Route as ExperiencesExperienceIdEditImport } from "./routes/experiences/$experienceId.edit";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ExperiencesExperienceIdRoute = ExperiencesExperienceIdImport.update({
  id: "/experiences/$experienceId",
  path: "/experiences/$experienceId",
  getParentRoute: () => rootRoute,
} as any);

const ExperiencesExperienceIdEditRoute =
  ExperiencesExperienceIdEditImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => ExperiencesExperienceIdRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/experiences/$experienceId": {
      id: "/experiences/$experienceId";
      path: "/experiences/$experienceId";
      fullPath: "/experiences/$experienceId";
      preLoaderRoute: typeof ExperiencesExperienceIdImport;
      parentRoute: typeof rootRoute;
    };
    "/experiences/$experienceId/edit": {
      id: "/experiences/$experienceId/edit";
      path: "/edit";
      fullPath: "/experiences/$experienceId/edit";
      preLoaderRoute: typeof ExperiencesExperienceIdEditImport;
      parentRoute: typeof ExperiencesExperienceIdImport;
    };
  }
}

// Create and export the route tree

interface ExperiencesExperienceIdRouteChildren {
  ExperiencesExperienceIdEditRoute: typeof ExperiencesExperienceIdEditRoute;
}

const ExperiencesExperienceIdRouteChildren: ExperiencesExperienceIdRouteChildren =
  {
    ExperiencesExperienceIdEditRoute: ExperiencesExperienceIdEditRoute,
  };

const ExperiencesExperienceIdRouteWithChildren =
  ExperiencesExperienceIdRoute._addFileChildren(
    ExperiencesExperienceIdRouteChildren,
  );

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/experiences/$experienceId": typeof ExperiencesExperienceIdRouteWithChildren;
  "/experiences/$experienceId/edit": typeof ExperiencesExperienceIdEditRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/experiences/$experienceId": typeof ExperiencesExperienceIdRouteWithChildren;
  "/experiences/$experienceId/edit": typeof ExperiencesExperienceIdEditRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/experiences/$experienceId": typeof ExperiencesExperienceIdRouteWithChildren;
  "/experiences/$experienceId/edit": typeof ExperiencesExperienceIdEditRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/experiences/$experienceId"
    | "/experiences/$experienceId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/experiences/$experienceId" | "/experiences/$experienceId/edit";
  id:
    | "__root__"
    | "/"
    | "/experiences/$experienceId"
    | "/experiences/$experienceId/edit";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ExperiencesExperienceIdRoute: typeof ExperiencesExperienceIdRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesExperienceIdRoute: ExperiencesExperienceIdRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/experiences/$experienceId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/experiences/$experienceId": {
      "filePath": "experiences/$experienceId.tsx",
      "children": [
        "/experiences/$experienceId/edit"
      ]
    },
    "/experiences/$experienceId/edit": {
      "filePath": "experiences/$experienceId.edit.tsx",
      "parent": "/experiences/$experienceId"
    }
  }
}
ROUTE_MANIFEST_END */
